### ISSUE TITLE
peer-to-peer-code-review

### ISSUE THREAD

**Issue by JakariaJishan** [FevenSeyfu/Todo-List-app#3]
you did a good job, the application is working fine. Still, there is an issue I found.
- when I click for edit it is displaying to-do list two times.
![image](https://user-images.githubusercontent.com/73704727/215108661-9ddf9662-1135-4377-b657-5d6fd7e581d0.png)
- try to refactor readme.md file with proper documentation.

**Comment by FevenSeyfu** [comment]
Thank you @JakariaJishan for your feedback, I will work on the mentioned issues.
